### ISSUE TITLE
镜像下载地址打不开了

### ISSUE THREAD

**Issue by hanyuanzhong** [simagix/asterisk-rpi#1]
http://www.raspberry-asterisk.org/downloads/
这个镜像下载地址打不开,您有下载好的资源吗

**Comment by jamesgeddes** [comment]
_Response based on translation from [Google Translate](https://translate.google.com/?sl=auto&tl=en&text=%E8%BF%99%E4%B8%AA%E9%95%9C%E5%83%8F%E4%B8%8B%E8%BD%BD%E5%9C%B0%E5%9D%80%E6%89%93%E4%B8%8D%E5%BC%80%2C%E6%82%A8%E6%9C%89%E4%B8%8B%E8%BD%BD%E5%A5%BD%E7%9A%84%E8%B5%84%E6%BA%90%E5%90%97&op=translate)_

The project moved to http://www.raspbx.org/downloads/ however, it is no longer active, as a note on that page states,
> Many thanks to Ronald who continuously updated his project over the years. Due to personal reasons it is unfortunately currently not possible to update the original RasPBX again in order to support the latest Pi 4 hardware revisions.

The last version includes Asterisk 16 which was released in [2018](https://docs.asterisk.org/About-the-Project/Asterisk-Versions/).

---
_Translation by [Google Translate](https://translate.google.com/?sl=en&tl=zh-CN&text=The%20project%20moved%20to%20http%3A%2F%2Fwww.raspbx.org%2Fdownloads%2F%20however%2C%20it%20is%20no%20longer%20active%2C%20as%20a%20note%20on%20that%20page%20states%2C%0A%0A%20%20%20%20Many%20thanks%20to%20Ronald%20who%20continuously%20updated%20his%20project%20over%20the%20years.%20Due%20to%20personal%20reasons%20it%20is%20unfortunately%20currently%20not%20possible%20to%20update%20the%20original%20RasPBX%20again%20in%20order%20to%20support%20the%20latest%20Pi%204%20hardware%20revisions.%0A%0AThe%20last%20version%20includes%20Asterisk%2016%20which%20was%20released%20in%202018.&op=translate) |  [谷歌翻译翻译](https://translate.google.com/?sl=en&tl=zh-CN&text=The%20project%20moved%20to%20http%3A%2F%2Fwww.raspbx.org%2Fdownloads%2F%20however%2C%20it%20is%20no%20longer%20active%2C%20as%20a%20note%20on%20that%20page%20states%2C%0A%0A%20%20%20%20Many%20thanks%20to%20Ronald%20who%20continuously%20updated%20his%20project%20over%20the%20years.%20Due%20to%20personal%20reasons%20it%20is%20unfortunately%20currently%20not%20possible%20to%20update%20the%20original%20RasPBX%20again%20in%20order%20to%20support%20the%20latest%20Pi%204%20hardware%20revisions.%0A%0AThe%20last%20version%20includes%20Asterisk%2016%20which%20was%20released%20in%202018.&op=translate)_

该项目已移至 http://www.raspbx.org/downloads/ 但是，它不再活跃，正如该页面上的注释所述，

     非常感谢罗纳德多年来不断更新他的项目。 不幸的是，由于个人原因，目前无法再次更新原始 RasPBX 以支持最新的 Pi 4 硬件版本。

最后一个版本包括 2018 年发布的 Asterisk 16。

**Comment by hanyuanzhong** [comment]
> _基于[Google Translate翻译的回复](https://translate.google.com/?sl=auto&tl=en&text=%E8%BF%99%E4%B8%AA%E9%95%9C%E5%83%8F%E4%B8%8B%E8%BD%BD%E5%9C%B0%E5%9D%80%E6%89%93%E4%B8%8D%E5%BC%80%2C%E6%82%A8%E6%9C%89%E4%B8%8B%E8%BD%BD%E5%A5%BD%E7%9A%84%E8%B5%84%E6%BA%90%E5%90%97&op=translate)_
> 
> 该项目已移至http://www.raspbx.org/downloads/但是，它不再活跃，正如该页面上的注释所述，
> 
> > 非常感谢罗纳德多年来不断更新他的项目。不幸的是，由于个人原因，目前无法再次更新原始 RasPBX 以支持最新的 Pi 4 硬件版本。
> 
> [最后一个版本包括2018 年](https://docs.asterisk.org/About-the-Project/Asterisk-Versions/)发布的 Asterisk 16 。
> 
> _[谷歌翻译](https://translate.google.com/?sl=en&tl=zh-CN&text=The%20project%20moved%20to%20http%3A%2F%2Fwww.raspbx.org%2Fdownloads%2F%20however%2C%20it%20is%20no%20longer%20active%2C%20as%20a%20note%20on%20that%20page%20states%2C%0A%0A%20%20%20%20Many%20thanks%20to%20Ronald%20who%20continuously%20updated%20his%20project%20over%20the%20years.%20Due%20to%20personal%20reasons%20it%20is%20unfortunately%20currently%20not%20possible%20to%20update%20the%20original%20RasPBX%20again%20in%20order%20to%20support%20the%20latest%20Pi%204%20hardware%20revisions.%0A%0AThe%20last%20version%20includes%20Asterisk%2016%20which%20was%20released%20in%202018.&op=translate)翻译| [谷歌翻译翻译](https://translate.google.com/?sl=en&tl=zh-CN&text=The%20project%20moved%20to%20http%3A%2F%2Fwww.raspbx.org%2Fdownloads%2F%20however%2C%20it%20is%20no%20longer%20active%2C%20as%20a%20note%20on%20that%20page%20states%2C%0A%0A%20%20%20%20Many%20thanks%20to%20Ronald%20who%20continuously%20updated%20his%20project%20over%20the%20years.%20Due%20to%20personal%20reasons%20it%20is%20unfortunately%20currently%20not%20possible%20to%20update%20the%20original%20RasPBX%20again%20in%20order%20to%20support%20the%20latest%20Pi%204%20hardware%20revisions.%0A%0AThe%20last%20version%20includes%20Asterisk%2016%20which%20was%20released%20in%202018.&op=translate)_
> 
> 该项目已移至http://www.raspbx.org/downloads/，但它不再活跃，正如该页面上所述的注释，
> 
> ```
>  非常感谢罗纳德多年来不断更新他的项目。 不幸的是，由于个人原因，目前无法再次更新原始 RasPBX 以支持最新的 Pi 4 硬件版本。
> ```
> 
> 最后一个版本包括 2018 年发布的 Asterisk 16。

Ok, thank you very much for your answer
